// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Param is one visualizer control, described for a generic UI renderer. The set
 * is small and fixed, so the frontend can build the panel without a schema
 * library.
 */
export interface Param {
    "key": string;
    "label": string;

    /**
     * "int" | "float"
     */
    "kind": string;
    "min": number;
    "max": number;
    "step": number;
    "default": number;
}
