// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodecOption is one decoder choice. Auto is offered as its own row rather than
 * hidden, because an empty preference is a real choice the engine understands.
 */
export interface CodecOption {
    "name": string;
    "label": string;
}

/**
 * EffectChainInfo is the whole chain in processing order.
 */
export interface EffectChainInfo {
    "stages": EffectStageInfo[] | null;
}

/**
 * EffectKindInfo is one effect a chooser can offer.
 */
export interface EffectKindInfo {
    "kind": string;
    "impl": string;
    "label": string;
    "weight": number;
    "scripted": boolean;
}

/**
 * EffectMetersInfo is one stage's live meters with no schema or values. It is
 * the payload of the fast meter tick, kept lean so a ~30 Hz read never re-walks
 * the parameters the 4 Hz snapshot already carries.
 */
export interface EffectMetersInfo {
    "id": string;
    "meters": { [_ in string]?: number } | null;
}

/**
 * EffectParamInfo is one parameter description for a control to render.
 */
export interface EffectParamInfo {
    "key": string;
    "kind": number;
    "min": number;
    "max": number;
    "step": number;
    "unit": string;
    "options": string[] | null;
    "default": any;
    "label": string;
    "group": string;
    "widget": string;
}

/**
 * EffectReadingInfo describes one key that Meters reports, so a reading can be
 * drawn without the frontend knowing which effect produced it.
 */
export interface EffectReadingInfo {
    "key": string;
    "label": string;
    "unit": string;
    "min": number;
    "max": number;
    "kind": string;
}

/**
 * EffectStageInfo is one stage in the chain.
 */
export interface EffectStageInfo {
    "id": string;
    "kind": string;
    "impl": string;
    "label": string;
    "bypassed": boolean;
    "schema": EffectParamInfo[] | null;
    "values": { [_ in string]?: any } | null;
    "meters": { [_ in string]?: number } | null;
    "readings": EffectReadingInfo[] | null;
    "visuals": EffectVisualInfo[] | null;
}

/**
 * EffectVisualInfo declares a plot. Params are schema keys the curve is derived
 * from; Overlays are reading keys drawn live on top.
 */
export interface EffectVisualInfo {
    "kind": string;
    "params": string[] | null;
    "overlays": string[] | null;
    "xMin": number;
    "xMax": number;
    "yMin": number;
    "yMax": number;
}

/**
 * Options is the static chooser data.
 */
export interface Options {
    "codecs": CodecOption[] | null;
    "backends": string[] | null;
    "effects": string[] | null;
}

/**
 * PreviewConfig is the preview window. StartMs and LengthMs are milliseconds
 * from the start of the track; a LengthMs of 0 means "to the end". FadeMs is
 * the ramp at each edge, Loop repeats the window until the selection changes,
 * and Volume is the preview's own level in [0, 1].
 */
export interface PreviewConfig {
    "startMs": number;
    "lengthMs": number;
    "fadeMs": number;
    "loop": boolean;
    "volume": number;
}

/**
 * PreviewState is the preview's contribution to the snapshot: which row is
 * sounding, how far into the window, and whether it loops. Active is false
 * when no preview is running, which is the signal to draw nothing.
 */
export interface PreviewState {
    "active": boolean;
    "path": string;
    "position": number;
    "duration": number;
    "loop": boolean;
}

/**
 * QueueRow is one entry in the bound queue view. Title, Artist and Album are
 * the tags the tag index resolved for the track; they are empty until the
 * resolver lands, and the palette falls back to Name when they are. They are
 * on the row rather than behind a second call so the search reads one payload.
 * CoverID identifies the track's embedded art; the palette fetches the bytes
 * through QueueCover only for the rows on screen.
 */
export interface QueueRow {
    "index": number;
    "path": string;
    "name": string;
    "title": string;
    "artist": string;
    "album": string;
    "coverId": string;
    "active": boolean;
}

/**
 * Snapshot is the whole visible player state in one value, so the frontend has
 * a single subscription and a single source of truth.
 */
export interface Snapshot {
    "state": string;
    "path": string;
    "title": string;
    "artist": string;
    "album": string;

    /**
     * CoverID identifies the current artwork; the UI fetches the bytes through
     * Cover(id). It is empty when the track has no art, which is the signal to
     * fall back to the placeholder.
     */
    "coverId": string;

    /**
     * CoverMime is the artwork type the source declared. The shipped UI reads
     * the type from the data URL instead; this is here for a UI that wants the
     * source format, or that renders the bytes itself.
     */
    "coverMime": string;
    "codec": string;
    "container": string;

    /**
     * milliseconds
     */
    "position": number;

    /**
     * milliseconds
     */
    "duration": number;
    "volume": number;
    "queue": QueueRow[] | null;
    "queueIdx": number;
    "decoder": string;

    /**
     * DecoderPref is the saved decoder preference, which is what the chooser
     * selects. Decoder is the effective decoder for the current track, which is
     * more specific and would not match any option value.
     */
    "decoderPref": string;
    "backend": string;
    "sampleRate": number;
    "channels": number;
    "error": string;

    /**
     * Preview is the palette's audition state, so the palette can draw the
     * previewing row and its progress from the same payload as everything else.
     */
    "preview": PreviewState;
}

/**
 * SpectrumConfig is the visualizer shape the UI edits.
 */
export interface SpectrumConfig {
    "bars": number;
    "minHz": number;
    "maxHz": number;

    /**
     * FFT is the transform length. Zero means the shipped default, so an older
     * frontend that does not send the field still gets a working display.
     */
    "fft": number;
}

/**
 * YTMResult is one search hit, flattened for the frontend. Kind is the label a
 * row shows; only a song is playable today, and a row says so rather than
 * offering a control that does nothing.
 */
export interface YTMResult {
    "videoId": string;
    "title": string;
    "artist": string;
    "album": string;
    "durationMs": number;
    "kind": string;
    "explicit": boolean;
    "thumbnail": string;
    "playable": boolean;
}
