// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService owns the engine and the bridge to the frontend.
 * 
 * It is a Wails service, hence a singleton shared by every window, so all
 * mutable state is guarded. The engine itself is safe for concurrent use; what
 * needs protecting here is the UI's assembled view of it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as spectrum$0 from "./internal/spectrum/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEffect appends a stage and returns its ID. The stage is live when this
 * returns, so the caller can set a parameter on it immediately.
 */
export function AddEffect(kind: string, impl: string): $CancellablePromise<string> {
    return $Call.ByID(2932875270, kind, impl);
}

/**
 * AddYTMPlaylist resolves a YouTube Music playlist or album and adds its tracks
 * to the queue in catalogue order. The input is the share URL a listener copies
 * ("...?list=PL..."), a browse id, or a bare id. The catalogue metadata of every
 * track is cached as it is resolved, so a queue row shows its real title and art
 * before anything is played; the queue itself holds only "ytm:<videoId>"
 * references, which is all the engine ever sees.
 * 
 * When the queue is empty the playlist starts playing; an existing queue is
 * appended to, leaving the current track alone, which is the same rule Add files
 * and Add folder follow.
 */
export function AddYTMPlaylist(input: string): $CancellablePromise<void> {
    return $Call.ByID(3532982679, input);
}

/**
 * AppendYTM adds a YouTube Music track to the end of the queue without starting
 * it, which is what Shift+Enter on a search result means. A live track is left
 * alone; an empty queue simply gains its first entry.
 */
export function AppendYTM(videoID: string): $CancellablePromise<void> {
    return $Call.ByID(2115977784, videoID);
}

/**
 * ArtistAvatar returns a YouTube Music artist's avatar as an inline data URL,
 * or "" when there is none. It is the settings preview's source: the presence
 * itself only needs the URL, but the webview may not load the remote image, so
 * the preview asks for the bytes the backend already fetched. The lookup is
 * cached in memory and on disk, so repeated asks cost nothing.
 */
export function ArtistAvatar(artistID: string): $CancellablePromise<string> {
    return $Call.ByID(1413159162, artistID);
}

/**
 * ConfigureSpectrum replaces the visualizer shape. The frame is rebuilt, so the
 * range, the points and the transform size all take effect on the next tick.
 * Enabled is not part of the shape: it only gates the pump, so it can be
 * toggled without rebuilding the runner and losing the live window.
 */
export function ConfigureSpectrum(cfg: $models.SpectrumConfig): $CancellablePromise<void> {
    return $Call.ByID(3682469907, cfg);
}

/**
 * Cover returns the current track's artwork as an inline data URL, or an empty
 * string when the track has none. The snapshot carries only the id, so the
 * payload a UI redraws at 4 Hz stays small; the bytes cross the bridge once,
 * when the id changes. The cache is keyed by that id, so revisiting a track
 * does not re-decode its art.
 */
export function Cover(id: string): $CancellablePromise<string> {
    return $Call.ByID(1183065355, id);
}

/**
 * DiscordStatus reports the integration's state for the settings UI.
 */
export function DiscordStatus(): $CancellablePromise<$models.DiscordStatus> {
    return $Call.ByID(3279222562);
}

/**
 * EffectChain returns the chain in force with each stage's schema, values and
 * live meters. It is read on the snapshot tick, so the panel and its meters
 * update without a second subscription.
 */
export function EffectChain(): $CancellablePromise<$models.EffectChainInfo> {
    return $Call.ByID(1535342562);
}

/**
 * EffectKinds lists every registered effect implementation, so the registry tab
 * can offer each (kind, impl) pair with its label and script flag.
 */
export function EffectKinds(): $CancellablePromise<$models.EffectKindInfo[] | null> {
    return $Call.ByID(693267092);
}

/**
 * EffectMeters returns only the live meters of every stage that meters. It is
 * the fast tick's read: no schema, no values, so a moving gain-reduction needle
 * can update at ~30 Hz without the cost of the full chain snapshot.
 */
export function EffectMeters(): $CancellablePromise<$models.EffectMetersInfo[] | null> {
    return $Call.ByID(2722747439);
}

/**
 * EffectWindowOpen reports whether the effect window exists, so the main window
 * can label its button.
 */
export function EffectWindowOpen(): $CancellablePromise<boolean> {
    return $Call.ByID(3136939069);
}

/**
 * ImportEasyEffectsPreset shows the native picker, reads the chosen EasyEffects
 * preset, and replaces the effect chain with the imported one. The dialog is
 * owned by Go so the frontend needs no file-system permission of its own, the
 * same shape as OpenFiles. A cancelled dialog returns an empty result and
 * leaves the chain untouched.
 */
export function ImportEasyEffectsPreset(): $CancellablePromise<$models.PresetImportResult> {
    return $Call.ByID(2879237944);
}

/**
 * ImportEasyEffectsPresetData imports a preset from JSON already in hand. It is
 * the path a frontend uses when it holds the bytes (a paste, or a test), with
 * no dialog and no file access.
 */
export function ImportEasyEffectsPresetData(data: string): $CancellablePromise<$models.PresetImportResult> {
    return $Call.ByID(3749912320, data);
}

/**
 * InsertNextYTM queues a YouTube Music track to play after the current one,
 * which is what Enter on a search result means. With a track already sounding
 * the queue is spliced after it, so that track keeps playing; with nothing
 * sounding there is no "next", so the insert also starts the track.
 */
export function InsertNextYTM(videoID: string): $CancellablePromise<void> {
    return $Call.ByID(3049016008, videoID);
}

/**
 * LoadPaths adds the chosen files and folders to the queue. When nothing is
 * queued yet it replaces the (empty) queue and starts the first track; when a
 * queue already exists it appends, so adding a folder does not cut off or reset
 * the track that is playing. A folder is expanded to its playable files,
 * recursively and sorted, the same way the TUI reads a folder argument.
 */
export function LoadPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1185588344, paths);
}

/**
 * MoveEffect moves the stage with id to index to in processing order. The index
 * is a final index in the resulting list, matching the engine.
 */
export function MoveEffect(id: string, to: number): $CancellablePromise<void> {
    return $Call.ByID(1294347996, id, to);
}

export function Next(): $CancellablePromise<void> {
    return $Call.ByID(1009561457);
}

/**
 * OpenEffectWindow shows the effect window from the main window. The window is
 * a second view over this same service, so the chain and its meters are one
 * state seen twice rather than two engines.
 */
export function OpenEffectWindow(): $CancellablePromise<void> {
    return $Call.ByID(2421518153);
}

/**
 * OpenFiles shows the native picker and loads what it returns. The dialog is
 * owned by Go so the frontend does not need a file-system permission of its
 * own.
 */
export function OpenFiles(): $CancellablePromise<void> {
    return $Call.ByID(2270930871);
}

/**
 * OpenFolder shows the native folder picker and loads what is playable inside.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(2552389420);
}

/**
 * Options is the static chooser data the UI reads once, because neither list
 * changes at runtime.
 */
export function Options(): $CancellablePromise<$models.Options> {
    return $Call.ByID(415814782);
}

/**
 * PlayIndex starts queue row index.
 */
export function PlayIndex(index: number): $CancellablePromise<void> {
    return $Call.ByID(3907908118, index);
}

export function Prev(): $CancellablePromise<void> {
    return $Call.ByID(1588563293);
}

/**
 * PreviewConfig reads the preview window settings in force.
 */
export function PreviewConfig(): $CancellablePromise<$models.PreviewConfig> {
    return $Call.ByID(3365288066);
}

/**
 * PreviewStart begins previewing the queued track at path, or replaces the
 * current preview. It pauses the main track once for the session and resumes it
 * when the session ends, so arrow navigation never flaps the main track.
 * 
 * A YouTube Music reference is refused: the preview player is built with the
 * built-in sources only (direct URLs and local files), not the YTM provider, so
 * it could not open one and the failure would leave the main track paused for a
 * session that never produced a sound.
 */
export function PreviewStart(path: string): $CancellablePromise<void> {
    return $Call.ByID(3793691400, path);
}

/**
 * PreviewStop ends the preview and resumes the main track if the session had
 * paused it. It is safe to call when no preview is running.
 */
export function PreviewStop(): $CancellablePromise<void> {
    return $Call.ByID(757197420);
}

/**
 * QueueCover returns the artwork of one queued track as an inline data URL, or
 * an empty string when it has none. The palette asks only for the rows it is
 * about to draw, so a large queue never pays to decode art the user will not
 * see. The cache is keyed by the content id the row carries, so a repeat ask
 * and a track that reappears are both served without re-reading the file.
 */
export function QueueCover(path: string): $CancellablePromise<string> {
    return $Call.ByID(4120849334, path);
}

/**
 * RemoveEffect drops the stage with id.
 */
export function RemoveEffect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3726857945, id);
}

/**
 * SearchYTMSongs searches YouTube Music and returns the results a listener can
 * act on: songs first, then the other kinds, each labelled. The engine is not
 * involved; this is catalogue work, and it is the one call here that reaches
 * the network.
 */
export function SearchYTMSongs(query: string): $CancellablePromise<$models.YTMResult[] | null> {
    return $Call.ByID(2050862098, query);
}

/**
 * SeekTo repositions the current track. Milliseconds keep the bound signature
 * plain; the facade takes a time.Duration. It is named SeekTo rather than Seek
 * because Seek(int64) error is the io.Seeker shape by signature but not in
 * meaning, and a method that almost satisfies an interface should not look like
 * it does.
 */
export function SeekTo(ms: number): $CancellablePromise<void> {
    return $Call.ByID(1112987009, ms);
}

/**
 * SetBackend changes the playback backend, reopening the device.
 */
export function SetBackend(name: string): $CancellablePromise<void> {
    return $Call.ByID(2984651864, name);
}

/**
 * SetCodec changes the decoder preference. An empty name means automatic. Per
 * the facade, this applies to the next track: SwapDecoder on a live track
 * reopens it in place, which the UI confirms with the Swapped event.
 */
export function SetCodec(name: string): $CancellablePromise<void> {
    return $Call.ByID(3320687474, name);
}

/**
 * SetDiscordEnabled turns the integration on or off and remembers the choice.
 */
export function SetDiscordEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3996627121, on);
}

/**
 * SetEffectBypass toggles the standard bypass parameter of the live effect.
 */
export function SetEffectBypass(id: string, bypassed: boolean): $CancellablePromise<void> {
    return $Call.ByID(4041722937, id, bypassed);
}

/**
 * SetEffectParam applies one parameter to the live effect. It does not rebuild
 * the chain, so the effect's state survives the change.
 */
export function SetEffectParam(id: string, key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(1973958366, id, key, value);
}

/**
 * SetPreviewConfig replaces the preview window settings. The values are
 * normalized, so a UI can send what it has without clamping first.
 */
export function SetPreviewConfig(cfg: $models.PreviewConfig): $CancellablePromise<void> {
    return $Call.ByID(3789468178, cfg);
}

/**
 * SetShuffle turns baked shuffle on or off. On, the queue is reordered once and
 * advances follow that order; off restores the order the shuffle was taken from.
 */
export function SetShuffle(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3896707945, on);
}

/**
 * SetVolume sets the master gain in [0, 1].
 */
export function SetVolume(v: number): $CancellablePromise<void> {
    return $Call.ByID(671101282, v);
}

/**
 * Snapshot is the bound read the UI calls once on mount and then treats as
 * push-updated. It is cheap by the facade's contract, so a stray poll is fine.
 */
export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2048559412);
}

export function SpectrumConfig(): $CancellablePromise<$models.SpectrumConfig> {
    return $Call.ByID(4206727037);
}

/**
 * SpectrumSchema describes the visualizer controls; SpectrumConfig reports the
 * values in force. The transform is display-only, so these never touch the
 * engine.
 */
export function SpectrumSchema(): $CancellablePromise<spectrum$0.Param[] | null> {
    return $Call.ByID(1579347792);
}

/**
 * Stop ends playback but keeps the queue, so a later play reuses it.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2311398648);
}

/**
 * TogglePause flips between playing and paused. With nothing playing it starts
 * the current queue row, which is what a single play button means.
 */
export function TogglePause(): $CancellablePromise<void> {
    return $Call.ByID(1955254246);
}
