// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CodecOption is one decoder choice. Auto is offered as its own row rather than
 * hidden, because an empty preference is a real choice the engine understands.
 */
export interface CodecOption {
    "name": string;
    "label": string;
}

/**
 * Options is the static chooser data.
 */
export interface Options {
    "codecs": CodecOption[] | null;
    "backends": string[] | null;
    "effects": string[] | null;
}

/**
 * QueueRow is one entry in the bound queue view.
 */
export interface QueueRow {
    "index": number;
    "path": string;
    "name": string;
    "active": boolean;
}

/**
 * Snapshot is the whole visible player state in one value, so the frontend has
 * a single subscription and a single source of truth.
 */
export interface Snapshot {
    "state": string;
    "path": string;
    "title": string;
    "artist": string;
    "album": string;
    "codec": string;
    "container": string;

    /**
     * milliseconds
     */
    "position": number;

    /**
     * milliseconds
     */
    "duration": number;
    "volume": number;
    "queue": QueueRow[] | null;
    "queueIdx": number;
    "decoder": string;

    /**
     * DecoderPref is the saved decoder preference, which is what the chooser
     * selects. Decoder is the effective decoder for the current track, which is
     * more specific and would not match any option value.
     */
    "decoderPref": string;
    "backend": string;
    "sampleRate": number;
    "channels": number;
    "error": string;
}

/**
 * SpectrumConfig is the visualizer shape the UI edits.
 */
export interface SpectrumConfig {
    "bars": number;
    "minHz": number;
    "maxHz": number;
}
