// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService owns the engine and the bridge to the frontend.
 * 
 * It is a Wails service, hence a singleton shared by every window, so all
 * mutable state is guarded. The engine itself is safe for concurrent use; what
 * needs protecting here is the UI's assembled view of it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as spectrum$0 from "./internal/spectrum/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfigureSpectrum replaces the visualizer shape. The frame is rebuilt, so the
 * range and the points both take effect on the next tick.
 */
export function ConfigureSpectrum(cfg: $models.SpectrumConfig): $CancellablePromise<void> {
    return $Call.ByID(3682469907, cfg);
}

/**
 * LoadPaths replaces the queue with the chosen files and folders and starts it.
 * A folder is expanded to its playable files, recursively and sorted, the same
 * way the TUI reads a folder argument.
 */
export function LoadPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1185588344, paths);
}

export function Next(): $CancellablePromise<void> {
    return $Call.ByID(1009561457);
}

/**
 * OpenFiles shows the native picker and loads what it returns. The dialog is
 * owned by Go so the frontend does not need a file-system permission of its
 * own.
 */
export function OpenFiles(): $CancellablePromise<void> {
    return $Call.ByID(2270930871);
}

/**
 * OpenFolder shows the native folder picker and loads what is playable inside.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(2552389420);
}

/**
 * Options is the static chooser data the UI reads once, because neither list
 * changes at runtime.
 */
export function Options(): $CancellablePromise<$models.Options> {
    return $Call.ByID(415814782);
}

/**
 * PlayIndex starts queue row index.
 */
export function PlayIndex(index: number): $CancellablePromise<void> {
    return $Call.ByID(3907908118, index);
}

export function Prev(): $CancellablePromise<void> {
    return $Call.ByID(1588563293);
}

/**
 * SeekTo repositions the current track. Milliseconds keep the bound signature
 * plain; the facade takes a time.Duration. It is named SeekTo rather than Seek
 * because Seek(int64) error is the io.Seeker shape by signature but not in
 * meaning, and a method that almost satisfies an interface should not look like
 * it does.
 */
export function SeekTo(ms: number): $CancellablePromise<void> {
    return $Call.ByID(1112987009, ms);
}

/**
 * SetBackend changes the playback backend, reopening the device.
 */
export function SetBackend(name: string): $CancellablePromise<void> {
    return $Call.ByID(2984651864, name);
}

/**
 * SetCodec changes the decoder preference. An empty name means automatic. Per
 * the facade, this applies to the next track: SwapDecoder on a live track
 * reopens it in place, which the UI confirms with the Swapped event.
 */
export function SetCodec(name: string): $CancellablePromise<void> {
    return $Call.ByID(3320687474, name);
}

/**
 * SetVolume sets the master gain in [0, 1].
 */
export function SetVolume(v: number): $CancellablePromise<void> {
    return $Call.ByID(671101282, v);
}

/**
 * Snapshot is the bound read the UI calls once on mount and then treats as
 * push-updated. It is cheap by the facade's contract, so a stray poll is fine.
 */
export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2048559412);
}

export function SpectrumConfig(): $CancellablePromise<$models.SpectrumConfig> {
    return $Call.ByID(4206727037);
}

/**
 * SpectrumSchema describes the visualizer controls; SpectrumConfig reports the
 * values in force. The transform is display-only, so these never touch the
 * engine.
 */
export function SpectrumSchema(): $CancellablePromise<spectrum$0.Param[] | null> {
    return $Call.ByID(1579347792);
}

/**
 * Stop ends playback but keeps the queue, so a later play reuses it.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2311398648);
}

/**
 * TogglePause flips between playing and paused. With nothing playing it starts
 * the current queue row, which is what a single play button means.
 */
export function TogglePause(): $CancellablePromise<void> {
    return $Call.ByID(1955254246);
}
