// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService owns the engine and the bridge to the frontend.
 * 
 * It is a Wails service, hence a singleton shared by every window, so all
 * mutable state is guarded. The engine itself is safe for concurrent use; what
 * needs protecting here is the UI's assembled view of it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as spectrum$0 from "./internal/spectrum/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddEffect appends a stage and returns its ID. The stage is live when this
 * returns, so the caller can set a parameter on it immediately.
 */
export function AddEffect(kind: string, impl: string): $CancellablePromise<string> {
    return $Call.ByID(2932875270, kind, impl);
}

/**
 * ConfigureSpectrum replaces the visualizer shape. The frame is rebuilt, so the
 * range and the points both take effect on the next tick.
 */
export function ConfigureSpectrum(cfg: $models.SpectrumConfig): $CancellablePromise<void> {
    return $Call.ByID(3682469907, cfg);
}

/**
 * Cover returns the current track's artwork as an inline data URL, or an empty
 * string when the track has none. The snapshot carries only the id, so the
 * payload a UI redraws at 4 Hz stays small; the bytes cross the bridge once,
 * when the id changes. The cache is keyed by that id, so revisiting a track
 * does not re-decode its art.
 */
export function Cover(id: string): $CancellablePromise<string> {
    return $Call.ByID(1183065355, id);
}

/**
 * EffectChain returns the chain in force with each stage's schema, values and
 * live meters. It is read on the snapshot tick, so the panel and its meters
 * update without a second subscription.
 */
export function EffectChain(): $CancellablePromise<$models.EffectChainInfo> {
    return $Call.ByID(1535342562);
}

/**
 * EffectKinds lists every registered effect implementation, so the registry tab
 * can offer each (kind, impl) pair with its label and script flag.
 */
export function EffectKinds(): $CancellablePromise<$models.EffectKindInfo[] | null> {
    return $Call.ByID(693267092);
}

/**
 * EffectWindowOpen reports whether the effect window exists, so the main window
 * can label its button.
 */
export function EffectWindowOpen(): $CancellablePromise<boolean> {
    return $Call.ByID(3136939069);
}

/**
 * LoadPaths replaces the queue with the chosen files and folders and starts it.
 * A folder is expanded to its playable files, recursively and sorted, the same
 * way the TUI reads a folder argument.
 */
export function LoadPaths(paths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1185588344, paths);
}

/**
 * MoveEffect moves the stage with id to index to in processing order. The index
 * is a final index in the resulting list, matching the engine.
 */
export function MoveEffect(id: string, to: number): $CancellablePromise<void> {
    return $Call.ByID(1294347996, id, to);
}

export function Next(): $CancellablePromise<void> {
    return $Call.ByID(1009561457);
}

/**
 * OpenEffectWindow shows the effect window from the main window. The window is
 * a second view over this same service, so the chain and its meters are one
 * state seen twice rather than two engines.
 */
export function OpenEffectWindow(): $CancellablePromise<void> {
    return $Call.ByID(2421518153);
}

/**
 * OpenFiles shows the native picker and loads what it returns. The dialog is
 * owned by Go so the frontend does not need a file-system permission of its
 * own.
 */
export function OpenFiles(): $CancellablePromise<void> {
    return $Call.ByID(2270930871);
}

/**
 * OpenFolder shows the native folder picker and loads what is playable inside.
 */
export function OpenFolder(): $CancellablePromise<void> {
    return $Call.ByID(2552389420);
}

/**
 * Options is the static chooser data the UI reads once, because neither list
 * changes at runtime.
 */
export function Options(): $CancellablePromise<$models.Options> {
    return $Call.ByID(415814782);
}

/**
 * PlayIndex starts queue row index.
 */
export function PlayIndex(index: number): $CancellablePromise<void> {
    return $Call.ByID(3907908118, index);
}

export function Prev(): $CancellablePromise<void> {
    return $Call.ByID(1588563293);
}

/**
 * PreviewConfig reads the preview window settings in force.
 */
export function PreviewConfig(): $CancellablePromise<$models.PreviewConfig> {
    return $Call.ByID(3365288066);
}

/**
 * PreviewStart begins previewing the queued track at path, or replaces the
 * current preview. It pauses the main track once for the session and resumes it
 * when the session ends, so arrow navigation never flaps the main track.
 */
export function PreviewStart(path: string): $CancellablePromise<void> {
    return $Call.ByID(3793691400, path);
}

/**
 * PreviewStop ends the preview and resumes the main track if the session had
 * paused it. It is safe to call when no preview is running.
 */
export function PreviewStop(): $CancellablePromise<void> {
    return $Call.ByID(757197420);
}

/**
 * QueueCover returns the artwork of one queued track as an inline data URL, or
 * an empty string when it has none. The palette asks only for the rows it is
 * about to draw, so a large queue never pays to decode art the user will not
 * see. The cache is keyed by the content id the row carries, so a repeat ask
 * and a track that reappears are both served without re-reading the file.
 */
export function QueueCover(path: string): $CancellablePromise<string> {
    return $Call.ByID(4120849334, path);
}

/**
 * RemoveEffect drops the stage with id.
 */
export function RemoveEffect(id: string): $CancellablePromise<void> {
    return $Call.ByID(3726857945, id);
}

/**
 * SeekTo repositions the current track. Milliseconds keep the bound signature
 * plain; the facade takes a time.Duration. It is named SeekTo rather than Seek
 * because Seek(int64) error is the io.Seeker shape by signature but not in
 * meaning, and a method that almost satisfies an interface should not look like
 * it does.
 */
export function SeekTo(ms: number): $CancellablePromise<void> {
    return $Call.ByID(1112987009, ms);
}

/**
 * SetBackend changes the playback backend, reopening the device.
 */
export function SetBackend(name: string): $CancellablePromise<void> {
    return $Call.ByID(2984651864, name);
}

/**
 * SetCodec changes the decoder preference. An empty name means automatic. Per
 * the facade, this applies to the next track: SwapDecoder on a live track
 * reopens it in place, which the UI confirms with the Swapped event.
 */
export function SetCodec(name: string): $CancellablePromise<void> {
    return $Call.ByID(3320687474, name);
}

/**
 * SetEffectBypass toggles the standard bypass parameter of the live effect.
 */
export function SetEffectBypass(id: string, bypassed: boolean): $CancellablePromise<void> {
    return $Call.ByID(4041722937, id, bypassed);
}

/**
 * SetEffectParam applies one parameter to the live effect. It does not rebuild
 * the chain, so the effect's state survives the change.
 */
export function SetEffectParam(id: string, key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(1973958366, id, key, value);
}

/**
 * SetPreviewConfig replaces the preview window settings. The values are
 * normalized, so a UI can send what it has without clamping first.
 */
export function SetPreviewConfig(cfg: $models.PreviewConfig): $CancellablePromise<void> {
    return $Call.ByID(3789468178, cfg);
}

/**
 * SetVolume sets the master gain in [0, 1].
 */
export function SetVolume(v: number): $CancellablePromise<void> {
    return $Call.ByID(671101282, v);
}

/**
 * Snapshot is the bound read the UI calls once on mount and then treats as
 * push-updated. It is cheap by the facade's contract, so a stray poll is fine.
 */
export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(2048559412);
}

export function SpectrumConfig(): $CancellablePromise<$models.SpectrumConfig> {
    return $Call.ByID(4206727037);
}

/**
 * SpectrumSchema describes the visualizer controls; SpectrumConfig reports the
 * values in force. The transform is display-only, so these never touch the
 * engine.
 */
export function SpectrumSchema(): $CancellablePromise<spectrum$0.Param[] | null> {
    return $Call.ByID(1579347792);
}

/**
 * Stop ends playback but keeps the queue, so a later play reuses it.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2311398648);
}

/**
 * TogglePause flips between playing and paused. With nothing playing it starts
 * the current queue row, which is what a single play button means.
 */
export function TogglePause(): $CancellablePromise<void> {
    return $Call.ByID(1955254246);
}
